### ISSUE TITLE
 CatBoostError: catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: catboost_info

### ISSUE THREAD

**Issue by cleclegarcin79** [MAIF/eurybia#15]
Problem: when I runing `SD.compile()` on Databricks cluster I have this issue : `CatBoostError: catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: catboost_info`.
Related to this [issue] (https://github.com/catboost/catboost/issues/1891 ), I add `allow_writing_files=False` in the definition of datadrift_classifier in SmartDrift Class and the problem disappear.

Is it possible to add a optionnal parameter to set `allow_writing_files=False` in the definition of datadrift_classifier in SmartDrift Class ?

**Comment by githubyako** [comment]
Hi,
We don't see a use case for this option being anything other than False at all for now, so we'll just set it to False by default.
Thanks for bringing up this issue, a fix is in development and we'll release a minor version quickly.

**Comment by cleclegarcin79** [comment]
Ok nows is good for DataBricks users :)
