### ISSUE TITLE
Getting modulenotfound error while importing eurybia

### ISSUE THREAD

**Issue by PranavGuptInd** [MAIF/eurybia#36]
Hi,
I'm using Databricks to find data drift for a model, but when I install eurybia and try import, I keep getting 
ModuleNotFoundError: No module named 'tkinter'.
But, I think tkinter in pre intsalled in python, right? 
<img width="877" alt="image" src="https://user-images.githubusercontent.com/83913546/202894161-8a2b56ae-9ffa-4025-97cf-71328dab5f32.png">
Any help on how I can solve this issue?

**Comment by ThomasBouche** [comment]
Hi, 
Thanks for your issue,
We are not familiar with the Databricks environment, but we already had the same kind of feedback on our Shapash library, with another type of environment.

We will try to reproduce the error and see how to solve it.

If in the meantime, you find a solution, do not hesitate to share it in the issue

**Comment by armgilles** [comment]
Hey @PranavGuptInd 

On python 3.8 (for exemple) on fresh new env in Linux, I can't reproduce your problem (with or without eurybia install).

`tkinker` is install by default in Python 3.X (If I'm not mistaken). Can you give use some info on your OS, Python version, lib install ?

**Comment by PranavGuptInd** [comment]
> Hey @PranavGuptInd
> 
> On python 3.8 (for exemple) on fresh new env in Linux, I can't reproduce your problem (with or without eurybia install).
> 
> `tkinker` is install by default in Python 3.X (If I'm not mistaken). Can you give use some info on your OS, Python version, lib install ?

Hi, even for me when I tried with a new environment with no additional libraries installed, it worked fine. But, seems there are some conflicting dependencies with fbprophet, that's why I feel I'm getting this error.
Have you ever checked compatibility of this library with prophet? If not so, can you please recreate this environment and see if it works right for you?

**Comment by armgilles** [comment]
Can't reproduce your problem : 

New fresh env with eurybia & fbprophet
```bash
conda create python=3.8 --name test_env_py38 
conda activate test_env_py38
pip install eurybia
python -m pip install prophet
```

In python
```python
import eurybia
from eurybia.data.data_loader import data_loading
```

No error from my side. Can you try on your side ?

**Comment by PranavGuptInd** [comment]
> Can't reproduce your problem :
> 
> New fresh env with eurybia & fbprophet
> 
> ```shell
> conda create python=3.8 --name test_env_py38 
> conda activate test_env_py38
> pip install eurybia
> python -m pip install prophet
> ```
> 
> In python
> 
> ```python
> import eurybia
> from eurybia.data.data_loader import data_loading
> ```
> 
> No error from my side. Can you try on your side ?

[fbprophet.txt](https://github.com/MAIF/eurybia/files/10123412/fbprophet.txt)
Can you please try using this environment?

**Comment by armgilles** [comment]
Could you export your environment without build : 

`conda env export --no-builds > environment.yml`

By the way, Eurybia don't support Python 3.6 anymore.

**Comment by PranavGuptInd** [comment]
Sure, here's the file as requested. Unfortunately, can't share yml files here, hence sharing in text format
[prophet_nobuild.txt](https://github.com/MAIF/eurybia/files/10124157/prophet_nobuild.txt)

**Comment by armgilles** [comment]
Sorry can't create this environement on Linux : 

```bash
conda env create --name fbprophet --file=prophet_nobuild.yml --verbose

Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed
Traceback (most recent call last):
  File "/home/gillesa/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/home/gillesa/anaconda3/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/home/gillesa/anaconda3/lib/python3.8/site-packages/conda_env/cli/main_create.py", line 118, in execute
    result[installer_type] = installer.install(prefix, pkg_specs, args, env)
  File "/home/gillesa/anaconda3/lib/python3.8/site-packages/conda_env/installers/conda.py", line 31, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "/home/gillesa/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/home/gillesa/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/home/gillesa/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 275, in solve_final_state
    ssc = self._add_specs(ssc)
  File "/home/gillesa/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 565, in _add_specs
    explicit_pool = ssc.r._get_package_pool(self.specs_to_add)
  File "/home/gillesa/anaconda3/lib/python3.8/site-packages/conda/resolve.py", line 555, in _get_package_pool
    pool = self.get_reduced_index(specs)
  File "/home/gillesa/anaconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/gillesa/anaconda3/lib/python3.8/site-packages/conda/resolve.py", line 576, in get_reduced_index
    explicit_specs, features = self.verify_specs(explicit_specs)
  File "/home/gillesa/anaconda3/lib/python3.8/site-packages/conda/resolve.py", line 288, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound:
  - msys2-conda-epoch=20160418
  - m2w64-winpthreads-git=5.0.0.4634.697f757
  - m2w64-toolchain=5.3.0
  - ucrt=10.0.20348.0
  - mkl=2022.0.0
  - m2w64-toolchain_win-64=2.4.0
  - pywin32-ctypes=0.2.0
  - m2w64-tools-git=5.0.0.4592.90b8472
  - m2w64-binutils=2.25.1
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - vc=14.2
  - winpty=0.4.3
  - m2w64-mpc=1.0.3
  - pywinpty=2.0.2
  - m2w64-zlib=1.2.8
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-isl=0.16.1
  - m2w64-make=4.1.2351.a80a8b8
  - icc_rt=2019.0.0
  - m2w64-mpfr=3.1.4
  - m2w64-crt-git=5.0.0.4636.2595836
  - m2w64-gmp=6.1.0
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2
  - m2w64-gcc-objc=5.3.0
  - m2w64-pkg-config=0.29.1
  - m2w64-gcc-fortran=5.3.0
  - vs2015_runtime=14.29.30037
  - m2w64-gcc=5.3.0
  - m2w64-headers-git=5.0.0.4636.c0ad18a
  - m2w64-gcc-libs=5.3.0
  - libpython=2.2
  - m2w64-bzip2=1.0.6
  - m2w64-gcc-ada=5.3.0
  - m2w64-windows-default-manifest=6.4
  - m2w64-gcc-libgfortran=5.3.0
```

Could you give us a minimum environnement just if you can reproduce your problem ? Maybe a small `requirement.txt` file with `pip freeze > requirements.txt`

**Comment by PranavGuptInd** [comment]
Here
[requirements.txt](https://github.com/MAIF/eurybia/files/10124732/requirements.txt)

**Comment by armgilles** [comment]
Hop with this command : `pip list --format=freeze > requirements.txt` (Cf [source](https://stackoverflow.com/questions/62885911/pip-freeze-creates-some-weird-path-instead-of-the-package-version) )

**Comment by PranavGuptInd** [comment]
Done
[requirements.txt](https://github.com/MAIF/eurybia/files/10124828/requirements.txt)

**Comment by armgilles** [comment]
Well I try my best, but can't reproduce it !

On python 3.8.15 with your last `requirement.txt` and fighting with package versions and conflicting dependencies... At the end  I can run `eurybia` : 

![image](https://user-images.githubusercontent.com/8374843/204851625-d7a38767-6ff5-4903-a9b2-61aa7ec5f444.png)

Having hard time to install your environment, so have to comment some minor package (I think) like for example : 

```bash
# Windows 
ERROR: Ignored the following versions that require a different python version: 1.9.5 Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, <3.7
ERROR: Could not find a version that satisfies the requirement pywin32==302 (from versions: none)
ERROR: No matching distribution found for pywin32==302


# sip
ERROR: Ignored the following versions that require a different python version: 1.0 Requires-Python >3.5, < 3.8; 1.0.1 Requires-Python >3.5, < 3.8; 1.9.5 Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, <3.7
ERROR: Could not find a version that satisfies the requirement sip==4.19.13 (from versions: 5.0.0, 5.0.1, 5.1.0, 5.1.1, 5.1.2, 5.2.0, 5.3.0, 5.4.0, 5.5.0, 6.0.0, 6.0.1, 6.0.2, 6.0.3, 6.1.0, 6.1.1, 6.2.0, 6.3.0, 6.3.1, 6.4.0, 6.5.0, 6.5.1, 6.6.0, 6.6.1, 6.6.2, 6.7.0, 6.7.1, 6.7.2, 6.7.3, 6.7.4, 6.7.5)
ERROR: No matching distribution found for sip==4.19.13

# pycodestyle
ERROR: Cannot install -r requirements.txt (line 11) and pycodestyle==2.7.0 because these pack
[requirements_eurybia.txt](https://github.com/MAIF/eurybia/files/10125100/requirements_eurybia.txt)
age versions have conflicting dependencies.

The conflict is caused by:
    The user requested pycodestyle==2.7.0
    autopep8 1.6.0 depends on pycodestyle>=2.8.0

# cmdstanpy
The conflict is caused by:
    The user requested cmdstanpy==0.9.5
    prophet 1.0.1 depends on cmdstanpy==0.9.68

# Etc...
```

You can find my requirement here to test on your side from  : [requirements_eurybia.txt](https://github.com/MAIF/eurybia/files/10125103/requirements_eurybia.txt)

**Comment by armgilles** [comment]
@ThomasBouche you can close it I think.

@PranavGuptInd feel free to re open it if you have any new informations :)
